[package]
name = "nft_lending_protocol"
edition = "2024.beta"
version = "0.1.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
lending = "0x0"

# Remove the conflicting dev-addresses section or use a different address
# [dev-addresses]
# lending = "0x1"  # Use a different address if you need dev-addresses